### ISSUE TITLE
简单介绍下我的练手项目

### ISSUE THREAD

**Issue by xukaiyyds** [xukaiyyds/comments#4]
https://note.xukaiyyds.cn/post/38504f98 
 前言起初我是在看前端面试时看到这样一个问题： 你有自己的技术博客吗？用了哪些技术？ 项目由来其实博客这东西我大学时就已经开始玩了，不过技术有限，也折腾不出什么有价值的东西来，而且用的也都是静态博客，静态博客的优点就是比动态博客响应速度快，缺点是戳写文章比较繁杂，不如动态博客方便。...

**Comment by xukaiyyds** [comment]
bug修复的差不多了，累死我了，睡觉💤

**Comment by asdfsasadfsa** [comment]
6

**Comment by xukaiyyds** [comment]
ctrl + enter 提交评论测试
